spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: mysql://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S08P12E108?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: S08P12E108
    password: LGBmz7o81b