spring:
  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

  security:
    oauth2:
      client:
        registration:
          github:
            clientId: cab357ccdc1b39a9a54b
            client-secret: 8d114cb3161d503734e173fd3e4b6fb118c5fca5
            redirect-uri: https://api.try-catch.duckdns.org/login/oauth2/code/github
            scope:
              - user:email
              - read:user

apiPrefix:
  v1