server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

logging:
  level:
    root: debug

spring:
  main:
    banner-mode: console
  profiles:
    active: local

apiPrefix:
  v1

---

spring:
  config:
    activate:
      on-profile: local

---

spring:
  config:
    activate:
      on-profile: dev

---

spring:
  config:
    activate:
      on-profile: prod
