GET localhost:8080/v1/feed/search?q=react
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnaG9feFlBdUphSG1WVXZPdmJFcnJ2bWQ3ekMyR2ZQVFdDMnY0TlpwIiwiaWQiOiIzIiwiaWF0IjoxNjc1MzE1MTE0LCJleHAiOjE2NzUzNTgzMTR9.L_XDjHNIL8PgWP8cNs7eGhEVue_V7129g2rhXifS12A
Refresh: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnaG9feFlBdUphSG1WVXZPdmJFcnJ2bWQ3ekMyR2ZQVFdDMnY0TlpwIiwiaWQiOiIzIiwiaWF0IjoxNjc1MzE1MTE0LCJleHAiOjE2NzU0MDE1MTR9.t94fNgs72El0k8KMsn1fcgWwEIRF60lkBkwftpdKBvc